namespace PaintingManager.Catalogue;

public class PaintRepository
{
    private List<Brand> _brands = new();
    public PaintRepository()
    {
        var armyPainter = new Brand("TheArmyPainter");

        _brands.Add(armyPainter);

        var apFanatics = new Series(armyPainter, "Warpaints Fanatics");

        armyPainter.AddSeries(apFanatics);

        apFanatics.AddPaint(new Paint(apFanatics, "Matt Black", "#000000", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Deep Grey", "#595d66", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Uniform Grey", "#6f737c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Ash Grey", "#8d9194", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Company Grey", "#c0c1c6", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Brigade Grey", "#d5d5d7", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Castle Grey", "#9c9992", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Gargoyle Grey", "#b3ac9c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Great Hall Grey", "#c6bdae", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Worn Stone", "#cec7b7", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Brainmatter Beige", "#e9e6d7", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Matt White", "#fdfdfd", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Night Sky", "#374757", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Thunderous Blue", "#365478", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Stratos Blue", "#33628c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Wolf Grey", "#5479a4", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Runic Cobalt", "#7c95b3", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Frost Blue", "#a5c0dd", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Triumphant Navy", "#1b2a53", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Gothic Blue", "#29386f", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Ultramarine Blue", "#274486", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Alpha Blue", "#6979b5", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Baron Blue", "#8697cd", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Augur Blue", "#b0c2ea", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Imperial Navy", "#003261", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Regal Blue", "#004a83", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Royal Blue", "#0055a8", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Crystal Blue", "#006dbf", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Arctic Gem", "#008ece", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Bright Sapphire", "#93ccea", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Deep Ocean Blue", "#213341", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Abyssal Blue", "#00506b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Tidal Blue", "#006a94", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Phalanx Blue", "#0086ac", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Shieldwall Blue", "#009ec5", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Aegis Aqua", "#3fadd0", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Deep Azure", "#016877", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Hydra Turqouise", "#018c93", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Turqouise Siren", "#25a9ae", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Aquamarine", "#59bec6", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Neptune Glow", "#7dccd1", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Marine Mist", "#9cd4d1", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Scarab Green", "#1e3b41", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Temple Gate Teal", "#005c4d", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Pharoah Guard", "#00755a", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Talisman Teal", "#00a585", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Aqua Alchemy", "#21b59b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Amulet Aqua", "#57cdb5", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Emerald Forest", "#52ad34", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Leafy Green", "#78bb0c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Rainforest", "#88d000", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Electric Lime", "#acd701", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Vivid Volt", "#d1e23c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Afterglow", "#e9ef8d", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Evergreen Fog", "#3d655c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Medieval Forest", "#457b6b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Patagon Pine", "#64917c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Autumn Sage", "#75ab93", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Forest Faun", "#a4c9aa", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Mossy Green", "#b8d8b9", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Woodland Camo", "#4f6347", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Army Green", "#61784a", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Camoflauge Green", "#728251", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Olive Drab", "#7e9056", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Necrotic Flesh", "#a1ac82", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Grotesque Green", "#b6c09b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Angel Green", "#1f3c2a", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Guardian Green", "#205f42", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Greenskin", "#097239", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Eternal Hunt", "#308c37", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Wild Green", "#44a244", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Ferocious Green", "#75c06b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Tundra Taupe", "#53533b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Prairie Ochre", "#6f6740", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Desert Yellow", "#88743f", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Wasteland Clay", "#a88a4c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Burnt Turf", "#c19c4e", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Barren Dune", "#dbba6b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Dusty Skull", "#928670", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Tomb King Tan", "#aa9a80", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Skeleton Bone", "#c1b696", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Ancient Stone", "#d4c9a9", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Boney Spikes", "#e9d9bf", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Pale Sand", "#f4ecd7", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Demigod Flames", "#d07733", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Fiendish Yellow", "#e39737", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Daemonic Yellow", "#ffca00", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Warped Yellow", "#f9d134", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Space Dust", "#f8e080", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Ice Yellow", "#fdebab", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Molten Lava", "#e84d31", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Burning Ore", "#f35c31", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Lava Orange", "#fa7310", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Flickering Flame", "#ff8b2c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Glowing Inferno", "#ffa837", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Inner Light", "#feca52", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Resplendent Red", "#972427", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Angelic Red", "#cd323a", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Legendary Red", "#e6382f", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Sacred Scarlet", "#ec563e", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Violent Vermillion", "#f0745a", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Raging Rouge", "#f28c7c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Brigadine Brown", "#443f3c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Bootstrap Brown", "#645250", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Leather Brown", "#806055", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Paratrooper Tan", "#9c7b6c", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Command Khaki", "#b99889", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Urban Buff", "#d6b5a6", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Basalisk Red", "#702738", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Wyvern Fury", "#923d48", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Dragon Red", "#94404b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Pure Red", "#a81719", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Blood Chalice", "#b33f42", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Raging Rose", "#b05453", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Oak Brown", "#524743", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Tree Ancient", "#615049", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Dryad Brown", "#6e5248", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Fur Brown", "#7f5651", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Ruddy Umber", "#875448", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Buffed Hide", "#a6776f", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Terrestial Titan", "#494753", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Alien Purple", "#665591", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Cultist Purple", "#7e69b1", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Hexed Violet", "#8877ad", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Violet Coven", "#9985af", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Kraken Lavender", "#b7acbe", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Wicked Pink", "#a91269", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Impish Rouge", "#be4586", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Pixie Pink", "#c5629b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Weird Elixer", "#b77a9e", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Pink Potion", "#ca99b6", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Doomfire Drab", "#c8afc0", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Mulled Berry", "#684852", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Moldy Wine", "#86485d", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Elder Flower", "#a0627e", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Forbidden Fruit", "#b37d92", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Figgy Pink", "#c39bab", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Wilted Rose", "#c5abb8", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Diabolic Plum", "#5c3b6b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Magecast Magenta", "#814b99", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Warlock Magenta", "#9453a2", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Spellbound Fuchia", "#b1559a", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Enchanted Pink", "#ab5f9b", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Diviner Light", "#c890bc", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Moonstone Skin", "#ad6f66", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Agate Skin", "#c67f75", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Barbarian Flesh", "#c98873", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Ruby Skin", "#ce9f8a", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Opal Skin", "#e5c2b7", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Pearl Skin", "#dbc9c0", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Obsidian Skin", "#56504f", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Onyx Skin", "#6c5851", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Mocca Skin", "#897164", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Amber Skin", "#a78d72", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Dorado Skin", "#c4a786", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Quartz Skin", "#d3baa0", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Carnelian Skin", "#644c4d", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Tigers Eye Skin", "#8d5958", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Topaz Skin", "#a46058", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Jasper Skin", "#9c6963", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Tourmaline Skin", "#a87a6e", PaintType.Opaque));
        apFanatics.AddPaint(new Paint(apFanatics, "Leopard Stone Skin", "#b99590", PaintType.Opaque));
        
        apFanatics.AddPaint(new Paint(apFanatics, "Dark Tone", "#252525", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Strong Tone", "#3a2a1d", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Soft Tone", "#72563e", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Light Tone", "#a06c1f", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Sepia Tone", "#93551f", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Rust Tone", "#573618", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Dark Red Tone", "#44212b", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Red Tone", "#5c202c", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Orange Tone", "#904115", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Green Tone", "#2c4831", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Military Shade", "#3b401d", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Blue Tone", "#1e3e5e", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Dark Blue Tone", "#293647", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Purple Tone", "#443256", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Magenta Tone", "#8e0e5b", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Strong Skin Shade", "#432724", PaintType.Wash));
        apFanatics.AddPaint(new Paint(apFanatics, "Dark Skin Shade", "#423337", PaintType.Wash));

        apFanatics.AddPaint(new Paint(apFanatics, "Rough Iron", "#362d25", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Red Copper", "#683d3f", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Weapon Bronze", "#b16716", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "True Copper", "#936143", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Evil Chrome", "#7e5341", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "True Brass", "#8d8479", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Tainted Gold", "#6b6644", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Greedy Gold", "#ac7725", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Bright Gold", "#ae8b20", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Mithril", "#bbbdc0", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Shining Silver", "#94969a", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Plate Metal", "#6a6b6f", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Gun Metal", "#505155", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Cobalt Metal", "#31464a", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Death Metal", "#2a2a2a", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Dark Emerald", "#415129", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Glittering Green", "#2f7e4d", PaintType.Metalic));
        apFanatics.AddPaint(new Paint(apFanatics, "Gemstone Red", "#851f26", PaintType.Metalic));

    }

    public Paint[] GetAllPaints()
    {
        return _brands.First().Series.First().Paints.ToArray();
    }
}